networks:
  http_network:
    external: true
  app_network:
    external: false

services:
  db:
    image: mariadb:11
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    networks:
      - app_network

  webserver:
    image: "elbromasmc/cnr"
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ENABLE_SMTP=${ENABLE_SMTP}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAIL_TO=${MAIL_TO}
      - PORT=8080
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    networks:
      - http_network
      - app_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=http_network"
      - "traefik.http.routers.webserver.entrypoints=websecure"
      - "traefik.http.routers.webserver.rule=Host(`www.centronutricionalrodriguez.com`)"
      - "traefik.http.routers.webserver.service=webserver"
      - "traefik.http.routers.webserver.tls=true"
      - "traefik.http.routers.webserver.tls.certresolver=letsencrypt"
      - "traefik.http.routers.webserver.tls.domains[0].main=www.centronutricionalrodriguez.com"
      - "traefik.http.routers.webserver.tls.options=default"
      - "traefik.http.services.webserver.loadbalancer.server.port=8080"
      - "traefik.http.services.webserver.loadbalancer.server.scheme=http"
volumes:
  db-data: